[project]
name = "project-cnn"
version = "0.1.0"
description = "Here, I will train a convolutional neural network"
readme = "README.md"
authors = [
    { name = "EddyGiusepe", email = "eddychirinos.unac@gmail.com" }
]
requires-python = ">=3.13.7, <3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "keras>=3.15.1",
    "matplotlib>=3.11.1",
    "tensorflow[and-cuda]>=2.21.0",
    "torch>=2.13.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.1",
]

[tool.ruff]
extend = "ruff.toml"
